package com.divinitor.discord.wahrbot.core.command;

public interface CommandRegistry {

    /**
     * Executes a command for the given command line, if valid.
     * @param commandLine The command line to execute
     * @param context The command execution context
     * @return The result of the command
     */
    CommandResult execute(String commandLine, CommandContext context);

    /**
     * Sets the parent of this command registry. Used for subcommand chaining
     * @param parent The new parent of this registry, or null if this will be a root registry
     * @throws IllegalArgumentException If a cyclical graph is created
     */
    void setParent(CommandRegistry parent) throws IllegalArgumentException;

    /**
     * Gets this registry's parent, or null if this is a root registry.
     * @return This registry's parent or null
     */
    CommandRegistry getParent();

    /**
     * @return If this registry is a root registry
     */
    default boolean isRoot() {
        return this.getParent() == null;
    }

    /**
     * Gets the command for the given command line and context.
     * @param commandLine The command line
     * @param context The command execution context
     * @return The command that matches the command line and context, or null if no match
     */
    Command getCommandFor(String commandLine, CommandContext context);

    /**
     * Determines whether or not the given command line in the given context can be executed.
     * @param commandLine The command line
     * @param context The command execution context
     * @return True if the execution would be allowed, false otherwise.
     */
    boolean hasPermissionFor(String commandLine, CommandContext context);

    /**
     * Sets the default command to be executed if no subcommands are specified. Cannot be set on the root registry. By
     * default this will be the autogenerated help command.
     * @param command The command to be executed by default if no subcommands are specified.
     */
    void setDefaultCommand(Command command);

    /**
     * Register a command to this command registry. Its full command path will be a space separated list of the registry
     * path followed by the resolved command locale key.
     * @param command The command to register
     * @param commandKey The command's base locale key
     */
    void registerCommand(Command command, String commandKey);
}
